### PR TITLE
Added Milligram CSS framework and created a basic two-column page layout

### PR DESCRIPTION
**Pull request by evan10s**
Also fixed a bunch of CSS related issues to make everything pretty again

### CODE REVIEW

**Comment by evan10s** [comment]
It seems like some of the navbar links are broken and only the first link works for the responsive navbar, so I'm gonna take a look at that

**Comment by illegalprime** [comment]
I know its not part of this PR, but this is cut off:
image

I fixed it by removing `padding-right` from this rule:
```css
.svg-icon {
    width: 16px;
    height: 16px;
    display: inline-block;
    fill: #828282;
    padding-right: 5px;
    vertical-align: text-top;
}
```

**Comment by illegalprime** [comment]
Also you're right about the navbar links, my guess is that they are behind the content of the page:
image

**Comment by illegalprime** [comment]
Also the menu button has extra space below it, which makes it look kinda weird:
image

Maybe fix that and add some CSS animation to open / close the menu?

**Review by illegalprime — CHANGES_REQUESTED** [review]
Just those three things and it should be good to go!

**Comment by illegalprime** [comment]
All that's left is:
- [x] fixing broken links in the navbar
- [x] maybe adding a CSS animation for the mobile menu?

**Comment by kexin-zhang** [comment]
This a bit nitpicky, but I feel like the margins on the side are a little too big. I think it would look better if there was less whitespace on larger screens. Awesome job so far!

**Comment by evan10s** [comment]
The navbar links are broken because locally the pages don't require the .html.  on nginx, the server isn't configured to do this, hence the 404 pages

**Comment by evan10s** [comment]
I added an animation for when the nav menu is shown on mobile devices, but I'm open to feedback on the speed and style of the animation.  There's no hide animation for the menu, mainly because I was having trouble figuring out how to do that 😕.  I think this is minor, though, because most of the time the nav menu being opened will end in the page being reloaded.

**Comment by evan10s** [comment]
@kexin-zhang I changed the width of the content area to match that of the new org site.  Is it better now?

**Review by kexin-zhang — APPROVED** [review]

**Review by illegalprime — APPROVED** [review]

**Pull request merged**
